spring:
   datasource:
      url: jdbc:mysql://localhost:3306/todolist?serverTimezone=Asia/Yekaterinburg&useUnicode=true&characterEncoding=utf8
      username: root
      password: Battery-10*-
   jpa:
     hibernate:
        ddl-auto: update
someParameter:
    value: 5463